name: Publish

on:
  push:
    tags:
      - "*"
  pull_request:
    tags:
      - "*"

env:
  PROJECT_PATH: "SiemensIXBlazor/SiemensIXBlazor.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Make build-npm.sh executable
        run: chmod +x ./build-npm.sh

      - name: Run build-npm.sh
        run: ./build-npm.sh

      - name: Build Project
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: Test with the dotnet CLI
        run: dotnet test

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2

      - name: "Pack Project"
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Push Package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate --no-symbols
